### ISSUE TITLE
Error with invokable controller

### ISSUE THREAD

**Issue by tanthammar** [fidum/laravel-blueprint-pestphp-addon#33]
```yaml
Report:
    __invoke:
      dispatch: GenerateReport with:event
      notify: auth.user ReportGenerated with:report
      render: report
```

Error:
```
  Undefined array key 1

  at vendor/fidum/laravel-blueprint-pestphp-addon/src/Builders/Statements/DispatchStatementBuilder.php:32
     28▕                 if (Str::studly(Str::singular($data)) === $this->context) {
     29▕                     $variables[] .= '$'.$data;
     30▕                     $conditions[] .= sprintf('$job->%s->is($%s)', $data, $data);
     31▕                 } else {
  ➜  32▕                     [$model, $property] = explode('.', $data);
     33▕                     $variables[] .= '$'.$model;
     34▕                     $conditions[] .= sprintf('$job->%s == $%s', $property ?: $model,
     35▕                         str_replace('.', '->', $data()));
     36▕                 }

      +22 vendor frames 
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```
